// <auto-generated />
using System;
using AkkuChatbot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkkuChatbot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502143344_MatchExistingDb")]
    partial class MatchExistingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkkuChatbot.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CoinBalance")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AkkuChatbot.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanvasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("AkkuChatbot.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentKind")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinsUsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IncludeInContext")
                        .HasColumnType("bit");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AkkuChatbot.Models.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCoinsUsed")
                        .HasColumnType("int");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("int");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("AkkuChatbot.Models.CoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoinTransactions");
                });

            modelBuilder.Entity("AkkuChatbot.Models.SessionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionGroups");
                });

            modelBuilder.Entity("AkkuChatbot.Models.SessionGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionGroupMembers");
                });

            modelBuilder.Entity("AkkuChatbot.Models.UserPromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CoinAwarded")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FluxModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GuidanceScale")
                        .HasColumnType("float");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPromptTemplates");

                    b.HasData(
                        new
                        {
                            Id = -101,
                            Category = "Cinematic",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-realism",
                            GuidanceScale = 7.5,
                            Height = 1536,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "blurry, low quality, text errors",
                            Prompt = "Create a cinematic movie poster for: [film title]. Genre: [action/drama/horror/sci-fi]. Include dramatic lighting, a central hero/villain figure, and a tagline at the bottom. Ultra-detailed, 4K, film grain.",
                            Steps = 30,
                            Style = "Movie Poster",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=101",
                            Title = "Cinematic Movie Poster",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -102,
                            Category = "Digital Art",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-anime",
                            GuidanceScale = 8.0,
                            Height = 1152,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "deformed, ugly, bad anatomy",
                            Prompt = "Fantasy character portrait of: [character name]. Race: [elf/dwarf/orc/human]. Class: [mage/warrior/rogue]. Magical glowing eyes, intricate armor, mystical background, highly detailed digital painting.",
                            Steps = 30,
                            Style = "Fantasy",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=102",
                            Title = "Fantasy Character Portrait",
                            UserId = "system",
                            Width = 896
                        },
                        new
                        {
                            Id = -103,
                            Category = "Photography",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.0,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "modern, digital, sharp",
                            Prompt = "Vintage travel poster for: [destination]. Style: 1920s Art Deco. Colors: muted retro palette. Paper texture, distressed edges, nostalgic feel.",
                            Steps = 25,
                            Style = "Vintage",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=103",
                            Title = "Vintage Travel Poster",
                            UserId = "system",
                            Width = 768
                        },
                        new
                        {
                            Id = -104,
                            Category = "Photography",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-realism",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "blurry, watermark, distorted",
                            Prompt = "Photorealistic product packaging mockup for: [product name]. Box on a white background, studio lighting, 8K, with brand logo, ingredients list, and barcode. Marketing-ready.",
                            Steps = 28,
                            Style = "Product",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=104",
                            Title = "Product Packaging Mockup",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -105,
                            Category = "Digital Art",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "any-dark",
                            GuidanceScale = 6.0,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "color, photograph, digital",
                            Prompt = "Ink sketch of: [subject]. Black ink on off-white paper, cross-hatching, expressive lines, no color, high contrast, artistic, fine art style.",
                            Steps = 20,
                            Style = "Sketch",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=105",
                            Title = "Monochrome Ink Sketch",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -106,
                            Category = "Code",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Optimize the following SQL query. Add proper indexes, rewrite inefficient joins, use CTEs where beneficial, and explain performance gains.",
                            Steps = 20,
                            Style = "SQL",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=106",
                            Title = "SQL Query Optimizer",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -107,
                            Category = "Code",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Debug this Python code. Identify syntax errors, logical mistakes, and edge cases. Provide fixed code with comments explaining each correction.",
                            Steps = 20,
                            Style = "Python",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=107",
                            Title = "Python Debugger Assistant",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -108,
                            Category = "Code",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Generate OpenAPI (Swagger) documentation for the following API endpoints. Include request/response schemas, example values, error codes, and authentication method.",
                            Steps = 20,
                            Style = "API",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=108",
                            Title = "REST API Documentation",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -109,
                            Category = "Writing",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Write a persuasive sales email for: [product/service]. Target audience: [description]. Highlight benefits, include urgency and end with a clear call-to-action.",
                            Steps = 20,
                            Style = "Sales",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=109",
                            Title = "Persuasive Sales Email",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -110,
                            Category = "Writing",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Write a detailed product review for: [product name]. Rating: 4.5/5. Include pros, cons, technical specifications, and a personal usage story.",
                            Steps = 20,
                            Style = "Review",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=110",
                            Title = "Product Review Amazon Style",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -111,
                            Category = "Writing",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Write a step-by-step guide on: [topic]. Include numbered steps, warnings, tool/materials list, and a troubleshooting section. Clear and beginner-friendly.",
                            Steps = 20,
                            Style = "Tutorial",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=111",
                            Title = "How-To Guide",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -112,
                            Category = "Writing",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Create a LinkedIn carousel post (6 slides) about: [topic]. Each slide has a heading, short bullet points, and an engaging question. End with a call-to-action.",
                            Steps = 20,
                            Style = "Social Media",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=112",
                            Title = "LinkedIn Carousel Post",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -113,
                            Category = "Analysis",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Explain how to calculate Return on Investment (ROI) for [project/software]. Provide formula, example with numbers, and interpretation of results.",
                            Steps = 20,
                            Style = "Business",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=113",
                            Title = "ROI Calculator Explanation",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -114,
                            Category = "Analysis",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Perform a SWOT analysis for [competitor name] in the [industry] sector. Include specific examples and strategic recommendations.",
                            Steps = 20,
                            Style = "Strategy",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=114",
                            Title = "SWOT Competitor Analysis",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -115,
                            Category = "Analysis",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "List 10 essential steps to clean a messy dataset. Include handling missing values, removing duplicates, standardizing formats, outlier detection.",
                            Steps = 20,
                            Style = "Data Science",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=115",
                            Title = "Data Cleaning Checklist",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -116,
                            Category = "Translate",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Translate the following text into Hinglish (Hindi written in Latin script). Keep the informal, friendly tone as if messaging a friend.",
                            Steps = 20,
                            Style = "Hinglish",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=116",
                            Title = "English to Hinglish Translation",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -117,
                            Category = "Translate",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Rewrite the following formal paragraph into casual, conversational style for WhatsApp. Use short sentences, contractions, and emojis.",
                            Steps = 20,
                            Style = "Casual",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=117",
                            Title = "Formal to Casual Rewriter",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -118,
                            Category = "Translate",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "Extract key terms from the following document and create a glossary. Sort alphabetically. Each entry: term - definition (one sentence).",
                            Steps = 20,
                            Style = "Technical Writing",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=118",
                            Title = "Glossary Creator",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -119,
                            Category = "Tamil",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "சிறந்த தமிழ் மேற்கோளை உருவாக்குக: [topic]. மேற்கோள் 15-25 வார்த்தைகளில் இருக்க வேண்டும். பாரம்பரிய தமிழ் இலக்கிய பாணியில் அமைய வேண்டும்.",
                            Steps = 20,
                            Style = "Quote",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=119",
                            Title = "Tamil Motivational Quote",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -120,
                            Category = "Tamil",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            Prompt = "தற்போதைய [topic] பற்றிய செய்தித் தலைப்பை எழுதுக. பத்திரிகை பாணியில், சுருக்கமாக, கவனத்தை ஈர்க்கும் வண்ணம். துணைத்தலைப்பும் சேர்க்கவும்.",
                            Steps = 20,
                            Style = "News",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=120",
                            Title = "Tamil News Headline",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -1,
                            Category = "Photography",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-realism",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "blurry, dark, shadow",
                            Prompt = "Professional product photography of [subject], white background, studio lighting, 8K",
                            Steps = 25,
                            Style = "Studio",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=1",
                            Title = "Photorealistic Product",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -2,
                            Category = "Digital Art",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-anime",
                            GuidanceScale = 8.0,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "blurry, low quality",
                            Prompt = "Digital concept art of [subject], vibrant colors, ArtStation trending, highly detailed",
                            Steps = 30,
                            Style = "Concept",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=2",
                            Title = "Digital Concept Art",
                            UserId = "system",
                            Width = 1024
                        },
                        new
                        {
                            Id = -5,
                            Category = "image",
                            CoinAwarded = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FluxModel = "flux-realism",
                            GuidanceScale = 7.5,
                            Height = 1024,
                            IsPublic = true,
                            IsSystem = true,
                            NegativePrompt = "cartoon, anime, painting",
                            Prompt = "Generate a photorealistic image of: [describe subject here]. Use natural lighting, high detail, 4K quality.",
                            Steps = 28,
                            Style = "Photorealistic",
                            ThumbnailUrl = "https://picsum.photos/120/80?random=5",
                            Title = "Photorealistic Image",
                            UserId = "system",
                            Width = 1024
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AkkuChatbot.Models.Artwork", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AkkuChatbot.Models.ChatMessage", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AkkuChatbot.Models.ChatSession", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AkkuChatbot.Models.CoinTransaction", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany("CoinTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AkkuChatbot.Models.SessionGroup", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AkkuChatbot.Models.SessionGroupMember", b =>
                {
                    b.HasOne("AkkuChatbot.Models.SessionGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AkkuChatbot.Models.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AkkuChatbot.Models.UserPromptTemplate", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkkuChatbot.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AkkuChatbot.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkkuChatbot.Models.ApplicationUser", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("CoinTransactions");
                });

            modelBuilder.Entity("AkkuChatbot.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AkkuChatbot.Models.SessionGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
